### PR TITLE
Add devtools and dirac options to template

### PR DESCRIPTION
**Pull request by pepe**
Use boot-cljs-devtools SNAPSHOT

### CODE REVIEW

**Comment by martinklepsch** [comment]
Thanks Josef for making these changes to boot-cljs-devtools and opening this PR. Great work. I'm already using the `cljs-devtools` task in a personal project 👍 

I'd prefer to wait until we have a non-snapshot release but I'm sure that won't take long. :)

**Comment by pepe** [comment]
You are welcome. 

I would also wait for non snapshot version. 

One more thing, I have on my mind is, that Dirac version is changing very often, so I volunteering for keeping Tenzing up to date with it 😉

**Comment by pepe** [comment]
Hello, boot-cljs-devtools stable was released, so everything is ready to go.

**Comment by martinklepsch** [comment]
Hey, sorry for the delay on this, currently on vacation so not much time spent on computer :)

I'll merge now and cut a release later today or tomorrow.

**Comment by pepe** [comment]
Oh sorry for bothering you then. Have nice times! And thank you very much. It is my first substantial Clojure OS work 😉, so I was eager to get it done.

**Pull request merged**
