### PR TITLE
Fixed boot-sass usage and added 'less' support.

### PR DESCRIPTION
**Pull request by ddeaguiar**
Sass changes were tested with the following sass dependency versions:

* sassc: 3.1.0
* libsass: 3.0.3
* sass2scss: 1.0.3

Less support provided by boot-less
(git@github.com:Deraen/boot-less.git) and supported by the +less option.

The `.main.less` less file suffix is [required](https://github.com/Deraen/boot-less/blob/master/src/deraen/boot_less.clj#L16) by boot-less.

All three css preprocessor options result in independent stylesheets.

### CODE REVIEW

**Comment by ddeaguiar** [comment]
Martin, I figured it would be easier for you if I recreated the pull request with changes based on your feedback.

**Comment by martinklepsch** [comment]
Thanks Daniel. Could you rebase against master? Should be only a minor conflict if at all. Thanks :)

**Comment by ddeaguiar** [comment]
Martin, rebase complete. Merge at your leisure :)

**Comment by martinklepsch** [comment]
Great. Thanks again :smile: 

I just pushed `0.3.0` to Clojars.

**Pull request merged**
